name: _
publish_to: none
environment:
  sdk: ^3.11.0
workspace:
  - example
  - packages/bloc_event_status
  - packages/bloc_event_status/example
  - packages/bloc_event_status_generator
  - packages/bloc_event_status_generator/example
