name: bloc_event_status
description: "Track the status of events in a bloc without updating the state."
version: 1.1.1
homepage: https://github.com/Jei-sKappa/bloc_event_status/tree/main/packages/bloc_event_status
repository: https://github.com/Jei-sKappa/bloc_event_status/tree/main/packages/bloc_event_status
issue_tracker: https://github.com/Jei-sKappa/bloc_event_status/issues
documentation: https://github.com/Jei-sKappa/bloc_event_status/tree/main/packages/bloc_event_status
topics: [bloc, state-management]

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: '>=8.0.0 <10.0.0'
  meta: ^1.15.0
  nested: ^1.0.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^7.0.0

flutter: null
