name: example
description: "BlocEventStatus' Example"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  bloc_event_status:
    path: ../
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  meta: ^1.15.0
  nested: ^1.0.0
  talker: ^4.7.2
  talker_bloc_logger: ^4.6.4
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true
