builders:
  bloc_event_status_generator:
    import: "package:bloc_event_status_generator/generator.dart"
    builder_factories: ["blocEventStatusGenerator"]
    build_extensions: {".dart": [".bes.g.dart"]}
    auto_apply: dependents
    build_to: source
